import { Player } from '../types';

export const POSITIONS_PT_BR: Record<string, string> = {
  GK: 'Goleiro',
  DC: 'Zagueiro',
  DL: 'Lateral Esquerdo',
  DR: 'Lateral Direito',
  WBL: 'Ala Esquerdo',
  WBR: 'Ala Direito',
  DM: 'Volante',
  ML: 'Meia Esquerda',
  MR: 'Meia Direita',
  MC: 'Meia Central',
  AML: 'Ponta Esquerda',
  AMR: 'Ponta Direita',
  AMC: 'Meia Atacante',
  ST: 'Atacante',
};

export const PT_ALIAS_TO_ID: Record<string, string> = {
  GOL: 'GK',
  ZAG: 'DC',
  LE: 'DL',
  LD: 'DR',
  ALE: 'WBL',
  ALD: 'WBR',
  VOL: 'DM',
  MEI: 'MC',
  ME: 'ML',
  MD: 'MR',
  MAE: 'AML',
  MAD: 'AMR',
  MAC: 'AMC',
  ATA: 'ST',
};

export const POSITION_ROLES: Record<string, Record<string, string[]>> = {
  ST: {
    Centroavante: [
      'finishing',
      'firstTouch',
      'heading',
      'technique',
      'composure',
      'offTheBall',
      'acceleration',
      'strength',
      'dribbling',
      'passing',
      'anticipation',
      'decisions',
      'agility',
      'balance',
      'jumping',
      'pace',
    ],
    'Encaminhamento por Canal': [
      'dribbling',
      'finishing',
      'firstTouch',
      'technique',
      'composure',
      'offTheBall',
      'workRate',
      'acceleration',
      'crossing',
      'heading',
      'passing',
      'anticipation',
      'decisions',
      'agility',
      'balance',
      'pace',
      'stamina',
    ],
    'Avançado Profundo': [
      'finishing',
      'firstTouch',
      'technique',
      'composure',
      'offTheBall',
      'strength',
      'dribbling',
      'passing',
      'anticipation',
      'decisions',
      'teamwork',
      'vision',
      'balance',
    ],
    'Falso Nove': [
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'acceleration',
      'finishing',
      'anticipation',
      'flair',
      'agility',
      'balance',
    ],
    'Caçador Furtivo': [
      'finishing',
      'heading',
      'anticipation',
      'composure',
      'concentration',
      'offTheBall',
      'acceleration',
      'firstTouch',
      'technique',
      'decisions',
      'balance',
    ],
    'Alvo Avançado': [
      'finishing',
      'heading',
      'aggression',
      'bravery',
      'composure',
      'offTheBall',
      'balance',
      'jumping',
      'strength',
      'firstTouch',
      'anticipation',
      'decisions',
      'teamwork',
    ],
  },
  AML: {
    'Ponta Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'composure',
      'teamwork',
      'acceleration',
      'agility',
      'crossing',
      'longShots',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
    'Ponta Criador de Jogo': [
      'crossing',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'acceleration',
      'anticipation',
      'flair',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    Ponta: [
      'crossing',
      'dribbling',
      'technique',
      'teamwork',
      'acceleration',
      'agility',
      'pace',
      'firstTouch',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'workRate',
      'balance',
      'stamina',
    ],
    'Atacante Aberto': [
      'dribbling',
      'firstTouch',
      'technique',
      'anticipation',
      'offTheBall',
      'acceleration',
      'agility',
      'pace',
      'crossing',
      'finishing',
      'passing',
      'composure',
      'flair',
      'workRate',
      'balance',
      'stamina',
    ],
    'Atacante Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'anticipation',
      'composure',
      'offTheBall',
      'acceleration',
      'agility',
      'crossing',
      'finishing',
      'longShots',
      'passing',
      'flair',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
  },
  AMR: {
    'Ponta Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'composure',
      'teamwork',
      'acceleration',
      'agility',
      'crossing',
      'longShots',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
    'Ponta Criador de Jogo': [
      'crossing',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'acceleration',
      'anticipation',
      'flair',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    Ponta: [
      'crossing',
      'dribbling',
      'technique',
      'teamwork',
      'acceleration',
      'agility',
      'pace',
      'firstTouch',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'workRate',
      'balance',
      'stamina',
    ],
    'Atacante Aberto': [
      'dribbling',
      'firstTouch',
      'technique',
      'anticipation',
      'offTheBall',
      'acceleration',
      'agility',
      'pace',
      'crossing',
      'finishing',
      'passing',
      'composure',
      'flair',
      'workRate',
      'balance',
      'stamina',
    ],
    'Atacante Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'anticipation',
      'composure',
      'offTheBall',
      'acceleration',
      'agility',
      'crossing',
      'finishing',
      'longShots',
      'passing',
      'flair',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
  },
  AMC: {
    'Meia Atacante': [
      'firstTouch',
      'longShots',
      'passing',
      'technique',
      'composure',
      'flair',
      'offTheBall',
      'crossing',
      'dribbling',
      'finishing',
      'anticipation',
      'decisions',
      'vision',
      'acceleration',
      'agility',
    ],
    'Meio-campista do Canal': [
      'crossing',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'offTheBall',
      'workRate',
      'acceleration',
      'dribbling',
      'longShots',
      'anticipation',
      'decisions',
      'flair',
      'vision',
      'agility',
      'pace',
      'stamina',
    ],
    'Papel Livre': [
      'dribbling',
      'firstTouch',
      'longShots',
      'passing',
      'technique',
      'composure',
      'flair',
      'offTheBall',
      'vision',
      'crossing',
      'finishing',
      'anticipation',
      'decisions',
      'acceleration',
      'agility',
    ],
    'Segundo Atacante': [
      'finishing',
      'firstTouch',
      'anticipation',
      'composure',
      'offTheBall',
      'acceleration',
      'dribbling',
      'longShots',
      'passing',
      'technique',
      'concentration',
      'decisions',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
  },
  ML: {
    'Meio-campista Aberto': [
      'crossing',
      'passing',
      'technique',
      'teamwork',
      'workRate',
      'pace',
      'stamina',
      'dribbling',
      'firstTouch',
      'anticipation',
      'composure',
      'offTheBall',
      'vision',
      'acceleration',
      'agility',
    ],
    'Ponta Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'composure',
      'teamwork',
      'acceleration',
      'agility',
      'crossing',
      'longShots',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
    'Ponta Criador de Jogo': [
      'crossing',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'acceleration',
      'anticipation',
      'flair',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    Ponta: [
      'crossing',
      'dribbling',
      'technique',
      'teamwork',
      'acceleration',
      'agility',
      'pace',
      'firstTouch',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'workRate',
      'balance',
      'stamina',
    ],
  },
  MR: {
    'Meio-campista Aberto': [
      'crossing',
      'passing',
      'technique',
      'teamwork',
      'workRate',
      'pace',
      'stamina',
      'dribbling',
      'firstTouch',
      'anticipation',
      'composure',
      'offTheBall',
      'vision',
      'acceleration',
      'agility',
    ],
    'Ponta Interior': [
      'dribbling',
      'firstTouch',
      'technique',
      'composure',
      'teamwork',
      'acceleration',
      'agility',
      'crossing',
      'longShots',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'vision',
      'workRate',
      'balance',
      'pace',
      'stamina',
    ],
    'Ponta Criador de Jogo': [
      'crossing',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'acceleration',
      'anticipation',
      'flair',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    Ponta: [
      'crossing',
      'dribbling',
      'technique',
      'teamwork',
      'acceleration',
      'agility',
      'pace',
      'firstTouch',
      'passing',
      'anticipation',
      'flair',
      'offTheBall',
      'workRate',
      'balance',
      'stamina',
    ],
  },
  MC: {
    'Meio-campista Central': [
      'firstTouch',
      'passing',
      'tackling',
      'decisions',
      'teamwork',
      'technique',
      'anticipation',
      'composure',
      'concentration',
      'offTheBall',
      'positioning',
      'vision',
      'workRate',
      'stamina',
    ],
    'Criador de Jogadas Avançado': [
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'crossing',
      'dribbling',
      'anticipation',
      'flair',
      'acceleration',
      'agility',
    ],
    'Meio-campista': [
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'dribbling',
      'tackling',
      'anticipation',
      'flair',
      'positioning',
      'workRate',
      'agility',
      'stamina',
    ],
    'Meio-campista Central Largo': [
      'firstTouch',
      'passing',
      'tackling',
      'decisions',
      'teamwork',
      'crossing',
      'dribbling',
      'technique',
      'anticipation',
      'composure',
      'concentration',
      'offTheBall',
      'positioning',
      'vision',
      'workRate',
      'agility',
      'stamina',
    ],
  },
  DM: {
    'Meio-Campo Defensivo': [
      'tackling',
      'anticipation',
      'concentration',
      'positioning',
      'teamwork',
      'firstTouch',
      'marking',
      'passing',
      'aggression',
      'composure',
      'decisions',
      'workRate',
      'stamina',
      'strength',
    ],
    'Meio-campista Box-to-Box': [
      'passing',
      'tackling',
      'offTheBall',
      'teamwork',
      'workRate',
      'stamina',
      'dribbling',
      'finishing',
      'firstTouch',
      'longShots',
      'technique',
      'aggression',
      'anticipation',
      'composure',
      'decisions',
      'positioning',
      'acceleration',
      'balance',
      'pace',
      'strength',
    ],
    'Criador de Jogo Box-to-Box': [
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'workRate',
      'stamina',
      'dribbling',
      'marking',
      'tackling',
      'anticipation',
      'positioning',
      'acceleration',
      'agility',
      'balance',
      'pace',
    ],
    'Deep-Lying Playmaker': [
      'firstTouch',
      'passing',
      'technique',
      'composure',
      'decisions',
      'offTheBall',
      'teamwork',
      'vision',
      'marking',
      'tackling',
      'anticipation',
      'concentration',
      'positioning',
      'workRate',
      'balance',
      'stamina',
    ],
    'Half-Back': [
      'heading',
      'marking',
      'tackling',
      'anticipation',
      'concentration',
      'positioning',
      'teamwork',
      'jumping',
      'strength',
      'firstTouch',
      'passing',
      'aggression',
      'bravery',
      'composure',
      'decisions',
      'workRate',
      'stamina',
    ],
  },
  WBL: {
    'Lateral Avançado': [
      'crossing',
      'dribbling',
      'technique',
      'offTheBall',
      'teamwork',
      'workRate',
      'acceleration',
      'agility',
      'pace',
      'stamina',
      'firstTouch',
      'marking',
      'passing',
      'tackling',
      'anticipation',
      'decisions',
      'flair',
      'positioning',
      'balance',
    ],
    'Lateral de Ponta': [
      'crossing',
      'marking',
      'tackling',
      'teamwork',
      'workRate',
      'acceleration',
      'pace',
      'stamina',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'anticipation',
      'concentration',
      'decisions',
      'offTheBall',
      'positioning',
      'agility',
      'balance',
    ],
  },
  WBR: {
    'Lateral Avançado': [
      'crossing',
      'dribbling',
      'technique',
      'offTheBall',
      'teamwork',
      'workRate',
      'acceleration',
      'agility',
      'pace',
      'stamina',
      'firstTouch',
      'marking',
      'passing',
      'tackling',
      'anticipation',
      'decisions',
      'flair',
      'positioning',
      'balance',
    ],
    'Lateral de Ponta': [
      'crossing',
      'marking',
      'tackling',
      'teamwork',
      'workRate',
      'acceleration',
      'pace',
      'stamina',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'anticipation',
      'concentration',
      'decisions',
      'offTheBall',
      'positioning',
      'agility',
      'balance',
    ],
  },
  DL: {
    Lateral: [
      'marking',
      'tackling',
      'anticipation',
      'concentration',
      'positioning',
      'teamwork',
      'acceleration',
      'crossing',
      'dribbling',
      'passing',
      'technique',
      'decisions',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    'Lateral Interior': [
      'heading',
      'marking',
      'tackling',
      'anticipation',
      'positioning',
      'strength',
      'dribbling',
      'aggression',
      'bravery',
      'composure',
      'concentration',
      'decisions',
      'workRate',
      'acceleration',
      'agility',
      'jumping',
      'pace',
      'stamina',
    ],
  },
  DR: {
    Lateral: [
      'marking',
      'tackling',
      'anticipation',
      'concentration',
      'positioning',
      'teamwork',
      'acceleration',
      'crossing',
      'dribbling',
      'passing',
      'technique',
      'decisions',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
    'Lateral Interior': [
      'heading',
      'marking',
      'tackling',
      'anticipation',
      'positioning',
      'strength',
      'dribbling',
      'aggression',
      'bravery',
      'composure',
      'concentration',
      'decisions',
      'workRate',
      'acceleration',
      'agility',
      'jumping',
      'pace',
      'stamina',
    ],
  },
  DC: {
    'Defensor Central': [
      'heading',
      'marking',
      'tackling',
      'anticipation',
      'positioning',
      'jumping',
      'strength',
      'aggression',
      'bravery',
      'composure',
      'concentration',
      'decisions',
      'workRate',
      'pace',
    ],
    'Defensor com Bola': [
      'heading',
      'marking',
      'passing',
      'tackling',
      'anticipation',
      'composure',
      'positioning',
      'jumping',
      'strength',
      'firstTouch',
      'technique',
      'aggression',
      'bravery',
      'concentration',
      'decisions',
      'vision',
      'pace',
    ],
    'Defensor Lateral': [
      'heading',
      'marking',
      'tackling',
      'anticipation',
      'positioning',
      'jumping',
      'strength',
      'crossing',
      'dribbling',
      'firstTouch',
      'passing',
      'technique',
      'aggression',
      'bravery',
      'composure',
      'concentration',
      'decisions',
      'workRate',
      'agility',
      'pace',
      'stamina',
    ],
  },
  GK: {
    Goleiro: [
      'reflexes',
      'handling',
      'command',
      'aerial',
      'oneOnOne',
      'kicking',
      'positioning',
      'communication',
      'throwing',
      'agility',
      'concentration',
      'decisions',
    ],
    'Goleiro Líbero': [
      'reflexes',
      'handling',
      'command',
      'aerial',
      'oneOnOne',
      'kicking',
      'positioning',
      'rushing',
      'passing',
      'firstTouch',
      'communication',
      'throwing',
      'agility',
      'concentration',
      'decisions',
      'acceleration',
      'composure',
      'vision',
    ],
  },
};

export const SUPPORTED_POSITIONS = Object.keys(POSITION_ROLES);

export const calculatePositionScore = (
  attributes: Record<string, number>,
  position: string
): number => {
  const posId = PT_ALIAS_TO_ID[position] || position;
  if (POSITION_ROLES[posId]) {
    const roleScores = Object.entries(POSITION_ROLES[posId]).map(
      ([role, roleAttrs]) => {
        let totalScore = 0;
        let count = 0;
        roleAttrs.forEach(attr => {
          const value = attributes[attr];
          if (value) {
            totalScore += value;
            count++;
          }
        });
        return count > 0 ? totalScore / count : 0;
      }
    );
    return Math.max(...roleScores, 0);
  }
  return 0;
};

export const getBestRoleAttributes = (
  attributes: Record<string, number>,
  position: string
): string[] => {
  const posId = PT_ALIAS_TO_ID[position] || position;
  if (!POSITION_ROLES[posId]) return [];

  let bestRole = '';
  let bestScore = -1;

  Object.entries(POSITION_ROLES[posId]).forEach(([role, attrs]) => {
    let totalScore = 0;
    let count = 0;
    attrs.forEach(attr => {
      const value = attributes[attr];
      if (value) {
        totalScore += value;
        count++;
      }
    });
    const score = count > 0 ? totalScore / count : 0;
    if (score > bestScore) {
      bestScore = score;
      bestRole = role;
    }
  });

  return bestRole ? POSITION_ROLES[posId][bestRole] : [];
};

export const getBestPositions = (
  player: Player
): { position: string; score: number }[] => {
  const scores = SUPPORTED_POSITIONS.map(pos => ({
    position: pos,
    // @ts-ignore
    score: calculatePositionScore(player.attributes, pos),
  }));

  return scores.sort((a, b) => b.score - a.score).slice(0, 3);
};
